apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: ns-tt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-svc
  template:
    metadata:
      labels:
        app: nginx-svc
    spec:
      containers:
        - image: nginx
          imagePullPolicy: Always
          name: nginx
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
              
---           
apiVersion: v1
kind: Service
metadata:
  name: nginx-services
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: nginx
  selector:
    app: nginx-svc
