apiVersion: v1
kind: Service
metadata:
  name: service-tt
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30001
  type: LoadBalancer

