apiVersion: v1
kind: Service
metadata:
  name: service-nginx
  namespace: ns-tt
spec:
  ports:
   - name: http
     port: 80
     targetPort: 80
     protocol: TCP
  type: LoadBalancer
  selector:
    app: web
