apiVersion: v1
kind: Service
metadata:
  name: service-tt-nlb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  selector:
    app: web2
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30002
  type: LoadBalancer

