apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replica
  namespace: ns-tt
  labels:
    app: web
    tier: web
spec:
  replicas: 1
  selector:
    matchLabels:        
      tier: web
  template:
    metadata:
      labels:
        tier: web
    spec:
      nodeSelector: 
        kops.k8s.io/instancegroup: nodes-ap-northeast-2a
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
